# Generated by Django 3.0.5 on 2021-10-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoftList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('soft_name', models.CharField(help_text='软件名称', max_length=30, unique=True, verbose_name='软件名称')),
                ('soft_img', models.TextField(help_text='软件图片base64', null=True, verbose_name='软件图片')),
                ('soft_path', models.CharField(help_text='软件路径，路由跳转路径', max_length=100, verbose_name='软件路径')),
                ('soft_desc', models.CharField(help_text='软件描述', max_length=255, null=True, verbose_name='软件描述')),
                ('is_del', models.CharField(default=0, help_text='有效状态', max_length=1, verbose_name='有效状态')),
            ],
            options={
                'verbose_name_plural': '软件列表',
                'db_table': 'cmdb_deploy_softlist',
            },
        ),
    ]
