# Generated by Django 3.0.5 on 2021-10-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EngineRoom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='机房名称', max_length=30, unique=True, verbose_name='机房名称')),
                ('location', models.CharField(help_text='机房位置', max_length=100, null=True, verbose_name='机房位置')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('text', models.CharField(help_text='备注', max_length=100, null=True, verbose_name='备注')),
                ('is_del', models.CharField(default=0, help_text='有效状态', max_length=1, verbose_name='有效状态')),
            ],
            options={
                'verbose_name_plural': '机房',
                'db_table': 'cmdb_engine_room',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='菜单名称', max_length=30, unique=True, verbose_name='菜单名称')),
                ('pid', models.CharField(help_text='父菜单ID', max_length=5, verbose_name='父菜单ID')),
                ('path', models.CharField(help_text='菜单路径', max_length=100, null=True, verbose_name='菜单路径')),
                ('icon', models.CharField(help_text='菜单图标', max_length=100, null=True, verbose_name='菜单图标')),
                ('is_del', models.CharField(default=0, help_text='有效状态', max_length=1, verbose_name='有效状态')),
            ],
            options={
                'verbose_name_plural': '菜单',
                'db_table': 'assets_menu',
            },
        ),
    ]
