# Generated by Django 3.0.5 on 2021-10-14 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='menu',
            table='cmdb_assets_menu',
        ),
    ]
