# Generated by Django 3.0.5 on 2021-10-25 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('private_ip_address', models.GenericIPAddressField(help_text='内网IP地址', verbose_name='内网IP地址')),
                ('public_ip_address', models.GenericIPAddressField(help_text='公网IP地址', null=True, verbose_name='公网IP地址')),
                ('os', models.CharField(default='', help_text='操作系统', max_length=255, null=True, verbose_name='操作系统')),
                ('type', models.CharField(default='', help_text='1.物理机，2.虚拟机，3.云服务器', max_length=255, null=True, verbose_name='服务器类型')),
                ('text', models.CharField(help_text='备注', max_length=100, null=True, verbose_name='备注')),
                ('username', models.CharField(default='', help_text='用户名', max_length=100, null=True, verbose_name='用户名')),
                ('password', models.CharField(default='', help_text='密码', max_length=100, null=True, verbose_name='密码')),
                ('port', models.CharField(default='', help_text='端口号', max_length=10, null=True, verbose_name='端口号')),
                ('engine_room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.EngineRoom')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.Project')),
            ],
            options={
                'verbose_name_plural': '服务器',
                'db_table': 'cmdb_server',
            },
        ),
    ]
