# Generated by Django 3.0.5 on 2021-10-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='type',
            field=models.CharField(default='', help_text='1.物理机\n2.虚拟机\n3.云服务器', max_length=255, null=True, verbose_name='服务器类型'),
        ),
    ]
