# Generated by Django 3.0.5 on 2021-10-25 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_machinetype_os'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='engine_room',
            field=models.ForeignKey(help_text='关联机房表', on_delete=django.db.models.deletion.PROTECT, to='assets.EngineRoom'),
        ),
        migrations.AlterField(
            model_name='server',
            name='os',
            field=models.ForeignKey(help_text='关联Os表', on_delete=django.db.models.deletion.PROTECT, to='assets.Os'),
        ),
        migrations.AlterField(
            model_name='server',
            name='project',
            field=models.ForeignKey(help_text='关联项目', on_delete=django.db.models.deletion.PROTECT, to='assets.Project'),
        ),
        migrations.AlterField(
            model_name='server',
            name='type',
            field=models.ForeignKey(help_text='关联机器类型表', on_delete=django.db.models.deletion.PROTECT, to='assets.MachineType'),
        ),
    ]
