# Generated by Django 3.0.5 on 2021-10-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_auto_20211025_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='is_del',
            field=models.CharField(default=0, help_text='有效状态', max_length=1, verbose_name='有效状态'),
        ),
    ]
