# Generated by Django 3.0.5 on 2021-11-03 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_server_is_del'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(help_text='服务名称', max_length=255, verbose_name='服务名称')),
                ('service_port', models.CharField(help_text='服务端口', max_length=100, null=True, verbose_name='服务端口')),
                ('service_dir', models.CharField(help_text='安装目录', max_length=1000, null=True, verbose_name='安装目录')),
                ('owner', models.CharField(help_text='启动用户', max_length=100, null=True, verbose_name='启动用户')),
                ('username', models.CharField(help_text='用户名', max_length=100, null=True, verbose_name='用户名')),
                ('password', models.CharField(help_text='密码', max_length=100, null=True, verbose_name='密码')),
                ('start_comm', models.CharField(help_text='启动命令', max_length=1000, null=True, verbose_name='启动命令')),
                ('restart_comm', models.CharField(help_text='重启命令', max_length=1000, null=True, verbose_name='重启命令')),
                ('stop_comm', models.CharField(help_text='停止命令', max_length=1000, null=True, verbose_name='停止命令')),
                ('text', models.CharField(help_text='备注', max_length=1000, null=True, verbose_name='备注')),
                ('belong_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Server')),
            ],
            options={
                'verbose_name_plural': '服务',
                'db_table': 'cmdb_services',
            },
        ),
    ]
