# Generated by Django 3.0.5 on 2021-11-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_services_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='service_version',
            field=models.CharField(help_text='服务版本', max_length=100, null=True, verbose_name='服务版本'),
        ),
    ]
