# Generated by Django 3.0.5 on 2021-11-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_services_service_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='enable_comm',
            field=models.CharField(help_text='开机启动命令', max_length=1000, null=True, verbose_name='开机启动命令'),
        ),
    ]
