# Generated by Django 3.0 on 2021-11-09 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_auto_20211104_0342'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('config_name', models.CharField(help_text='配置文件名称', max_length=2555, verbose_name='配置文件名称')),
                ('config_hash', models.CharField(help_text='minio映射名称', max_length=255, verbose_name='minio映射名称')),
                ('file_size', models.CharField(default='0', help_text='配置文件大小', max_length=255, verbose_name='配置文件大小')),
                ('file_type', models.CharField(help_text='配置文件格式', max_length=255, null=True, verbose_name='配置文件格式')),
                ('file_charset', models.CharField(help_text='配置文件字符集', max_length=255, null=True, verbose_name='配置文件字符集')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('belong_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Services')),
            ],
            options={
                'verbose_name_plural': '配置文件',
                'db_table': 'cmdb_config_file',
            },
        ),
    ]
