# Generated by Django 3.0 on 2021-11-29 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_serviceconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerRate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cpu_rate', models.CharField(help_text='CPU使用率', max_length=255, null=True, verbose_name='CPU使用率')),
                ('mem_rate', models.CharField(help_text='内存使用率', max_length=255, null=True, verbose_name='内存使用率')),
                ('disk_rate', models.CharField(help_text='磁盘使用率', max_length=2555, null=True, verbose_name='磁盘使用率')),
                ('update_time', models.DateTimeField(auto_now_add=True, help_text='上次更新时间', null=True, verbose_name='上次更新时间')),
                ('belong_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Server')),
            ],
            options={
                'verbose_name_plural': '服务器资源信息',
                'db_table': 'cmdb_server_rate',
            },
        ),
    ]
