# Generated by Django 3.0 on 2021-10-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CmdbAuth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='用户名', max_length=100, verbose_name='用户名')),
                ('password', models.CharField(help_text='密码', max_length=100, verbose_name='密码')),
                ('token', models.CharField(help_text='验证字符串', max_length=255, verbose_name='验证字符串')),
                ('is_admin', models.CharField(default=0, help_text='管理员', max_length=1, verbose_name='管理员')),
                ('is_del', models.CharField(default=0, help_text='是否有效', max_length=1, verbose_name='是否有效')),
            ],
            options={
                'verbose_name_plural': '登录认证',
                'db_table': 'cmdb_auth',
            },
        ),
    ]
